#!/bin/bash
src="https://github.com/somastash/${1}"
dst="$HOME/Desktop/${1}_$(date +%Y)"
if [ -e "$dst" ]; then
	echo "//// ERROR //// The destination: $dst already exists."
	exit 1
fi

command -v "git" &> /dev/null || xcode-select --install

if ! git clone --recurse-submodules "$src" "$dst"; then
	echo "//// ERROR //// git-clone failed."
	exit 1
fi

if [ ! -d "$dst" ]; then
	echo "//// ERROR //// $dst is not found after git-clone. There must be something wrong here..."
	exit 1
fi

echo
echo "---- SUCCESS ----"
echo "src: $src"
echo "dst: $dst"
echo "================="
echo
